name: Static Code Analysis

on:
  push:
    branches:
      - master # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the master branch

jobs:
  analyze:
    runs-on: ubuntu-latest  # Use Ubuntu environment for CI/CD

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python (if you need it for running your script)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Set Python version to 3.9 or any other version required

    # Step 3: Install dependencies (you may have a requirements.txt for Python dependencies)
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # This installs Python dependencies listed in requirements.txt

    # Step 4: Run the Static Analysis Script
    - name: Run Static Analysis
      run: python static_analyzer.py  # This runs your static analysis script

    # Step 5: Store and upload the results (optional, for analysis)
    - name: Upload Scan Results
      uses: actions/upload-artifact@v3
      with:
        name: scan-results
        path: scan_results.db  # Upload the scan results file (e.g., SQLite DB)

    # Optional: Post a summary or notifications if vulnerabilities are found
    - name: Post Analysis Summary
      run: |
        cat scan_results.db  # Output the results (you can modify this to suit your reporting needs)
